#!/bin/sh -eu

ZBIN=$ZEBRA_TEMP/intermediate.zbin

$ZEBRA import input.ztxt --schema input.zschema --output $ZBIN

echo "=== Schema ==="
$ZEBRA export $ZBIN --schema-stdout

echo
echo "=== Data ==="
$ZEBRA export $ZBIN --output-stdout

echo
echo "=== Summary ==="
$ZEBRA summary $ZBIN
